### ISSUE TITLE
The string "Using password from environment variable CODA_PRIVKEY_PASS" is in ledger export files

### ISSUE THREAD

**Issue by hsq125** [jrwashburn/mina-pool-payout#57] opened 2021-06-03 14:58 UTC
The string 

`"Using password from environment variable CODA_PRIVKEY_PASS"`

is at the beginning of the `staking-epoch-ledger.json `and  `next-epoch-ledger.json` files

Example 

```
Using password from environment variable CODA_PRIVKEY_PASS
[
  {
    "pk": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
    "balance": "0.000001",
    "delegate": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
    "token": "1",
    "token_permissions": {},
    "receipt_chain_hash":
      "2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe",
    "voting_for": "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
.....
```

**Comment by jrwashburn** [comment] 2021-06-03 16:46
I cannot reproduce this - how are you pulling the data? I am using this:
https://github.com/jrwashburn/mina-node-install/blob/main/scripts/mina-export-ledgers.sh

And none of the files have this. If you just directly run 
mina ledger export staking-epoch-ledger
Do you still have that first line?

**Comment by jrwashburn** [comment] 2021-06-04 10:23
This seems to be an issue with several CLI commands on docker - https://discord.com/channels/484437221055922177/754653322845356103/850183802215202847

**Comment by hsq125** [comment] 2021-06-04 10:34
Correct! I'm running it from the docker container

From my server
`mina@cs3:~/mina-pool-payout$ docker exec -it mina_mainnet_1 bash`

Then, when I'm in container

```
root@0932843fad2b:~# mina ledger export staking-epoch-ledger > /tmp/XXX.json
root@0932843fad2b:~# head /tmp/XXX.json 
Using password from environment variable CODA_PRIVKEY_PASS
[
  {
    "pk": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
    "balance": "0.000001",
    "delegate": "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg",
    "token": "1",
    "token_permissions": {},
    "receipt_chain_hash":
      "2mzbV7WevxLuchs2dAMY4vQBS6XttnCUF8Hvks4XNBQ5qiSGGBQe",
...
```

**Comment by hsq125** [comment] 2021-06-04 10:35
I temporarily fixed the issue with the following workaround 

```
GARBAGE="Using password from environment variable CODA_PRIVKEY_PASS"
mina ledger export staking-epoch-ledger | grep -v --regexp="$GARBAGE" > staking-epoch-ledger.json
```

**Comment by jrwashburn** [comment] 2021-06-04 10:42
Sounds good / nice hack. I think I'll close this as wontfix unless you object.

**Comment by hsq125** [comment] 2021-06-04 10:49
You can close it. Maybe just add this hack so problem is solved for people using docker.

**Comment by jrwashburn** [comment] 2021-06-04 10:55
Sounds good - I will add the hack to the export script here:
https://github.com/jrwashburn/mina-node-install/blob/main/scripts/mina-export-ledgers.sh

And also stole it for status monitor here:
https://github.com/jrwashburn/mina-node-install/blob/main/scripts/mina-status-monitor.sh

Thanks!

**Closed by jrwashburn** 2021-06-04 10:55 UTC
